name: bumper
description: git version bumping action
author: trev
branding:
  icon: anchor
  color: gray-dark

inputs:
  files:
    description: list of files to bump versions in
    required: false
  commit:
    description: commit changes after bumping
    required: false
    default: "true"
  push:
    description: push changes after bumping
    required: false
    default: "true"
  major_types:
    description: conventional commit types for MAJOR version bumps
    required: false
  minor_types:
    description: conventional commit types for MINOR version bumps
    required: false
  patch_types:
    description: conventional commit types for PATCH version bumps
    required: false
  skip_scopes:
    description: conventional commit scopes to skip over
    required: false
  force:
    description: force at least a PATCH version bump
    required: false
  debug:
    description: enable debug logging
    required: false

runs:
  using: docker
  image: docker://ghcr.io/spotdemo4/bumper:0.4.4
  env:
    FILES: ${{ inputs.files }}
    COMMIT: ${{ inputs.commit }}
    PUSH: ${{ inputs.push }}
    MAJOR_TYPES: ${{ inputs.major_types }}
    MINOR_TYPES: ${{ inputs.minor_types }}
    PATCH_TYPES: ${{ inputs.patch_types }}
    SKIP_SCOPES: ${{ inputs.skip_scopes }}
    FORCE: ${{ inputs.force }}
    DEBUG: ${{ inputs.debug }}
