name: bumper
description: git version bumping action
author: trev
branding:
  icon: anchor
  color: gray-dark

inputs:
  files:
    description: list of files to look for version strings
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if [ -z "$(git config user.name)" ]; then
          echo "no user found, using default"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        fi

        echo "git user: $(git config user.name) <$(git config user.email)>"

    - shell: bash
      run: |
        if command -v nix &> /dev/null && ! command -v nix-update &> /dev/null; then
          echo "nix-update not found, installing via nix"

          UPDATE=$(nix shell nixpkgs#nix-update \
            --inputs-from . \
            --command bash \
            -c "which nix-update")
          echo "nix-update installed at: ${UPDATE}"

          DIR=$(dirname "${UPDATE}")
          echo "adding nix-update to PATH: ${DIR}"

          echo "${DIR}" >> "${GITHUB_PATH}"
        fi

    - shell: bash
      run: |
        echo "${GITHUB_PATH}"
        echo "${PATH}"

        set +e
        ./bumper.sh ${{ inputs.files }}
        EXIT_CODE=$?
        set -e

        if [ "${EXIT_CODE}" -eq 2 ]; then
          echo "missing dependency, using fallback binary"
          wget "https://github.com/spotdemo4/bumper/releases/download/v0.1.7/bumper-linux-x86_64" -O bumper
          chmod +x bumper
          ./bumper ${{ inputs.files }}
        else
          exit ${EXIT_CODE}
        fi
