name: bumper
description: git version bumping action
author: trev
branding:
  icon: anchor
  color: gray-dark

inputs:
  files:
    description: files to bump versions in
    required: false
  major_types:
    description: conventional commit types for MAJOR version bumps
    required: false
  minor_types:
    description: conventional commit types for MINOR version bumps
    required: false
  patch_types:
    description: conventional commit types for PATCH version bumps
    required: false
  skip_scopes:
    description: conventional commit scopes to skip over
    required: false
  commit:
    description: commit changes after bumping
    required: false
    default: "true"
  tag:
    description: tag changes after bumping
    required: false
    default: "true"
  push:
    description: push changes after bumping
    required: false
    default: "true"
  force:
    description: force at least a PATCH version bump
    required: false
  allow_dirty:
    description: allow a dirty working directory
    required: false
  debug:
    description: enable debug logging
    required: false
    default: ${{ runner.debug }}

runs:
  using: docker
  image: docker://ghcr.io/spotdemo4/bumper:0.10.1
  env:
    PATHS: ${{ inputs.files }}
    MAJOR_TYPES: ${{ inputs.major_types }}
    MINOR_TYPES: ${{ inputs.minor_types }}
    PATCH_TYPES: ${{ inputs.patch_types }}
    SKIP_SCOPES: ${{ inputs.skip_scopes }}
    COMMIT: ${{ inputs.commit }}
    TAG: ${{ inputs.tag }}
    PUSH: ${{ inputs.push }}
    FORCE: ${{ inputs.force }}
    ALLOW_DIRTY: ${{ inputs.allow_dirty }}
    DEBUG: ${{ inputs.debug }}
