name: bumper
description: git version bumping action
author: trev
branding:
  icon: anchor
  color: gray-dark

inputs:
  files:
    description: list of files to look for version strings
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if [ -z "$(git config user.name)" ]; then
          echo "no user found, using default"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        fi

        echo "git user: $(git config user.name) <$(git config user.email)>"

    - shell: bash
      run: |
        if command -v nix &> /dev/null && ! command -v nix-update &> /dev/null; then
          echo "nix-update not found, installing via nix"

          UPDATE_PATH=$(nix shell nixpkgs#nix-update \
            --inputs-from . \
            --command bash \
            -c "which nix-update")
          echo "$(dirname "${UPDATE_PATH}")" >> "${GITHUB_PATH}"
        fi

    - shell: bash
      id: bumper
      run: |
        set +e
        ./bumper.sh ${{ inputs.files }}
        echo "exit_code=${?}" >> "${GITHUB_OUTPUT}"
        set -e

    - shell: bash
      if: ${{ steps.bumper.outputs.exit_code == '1' }}
      run: exit 1

    - shell: bash
      if: ${{ steps.bumper.outputs.exit_code == '2' }}
      run: |
        echo "missing dependency, falling back to binary"
        wget "https://github.com/spotdemo4/bumper/releases/download/v0.1.15/bumper-x86_64-linux" -O bumper
        chmod +x bumper
        ./bumper ${{ inputs.files }}
