name: bumper
description: git version bumping action
author: trev
branding:
  icon: anchor
  color: gray-dark

inputs:
  files:
    description: list of files to look for version strings
  skip_deps:
    description: skip installing dependencies if they are already installed

runs:
  using: composite
  steps:
    - if: ${{ inputs.skip_deps != 'true' }}
      shell: bash
      run: |
        wget https://github.com/spotdemo4/bumper/releases/download/v0.0.4/bumper_0.0.4_amd64.deb
        sudo dpkg -i bumper_0.0.4_amd64.deb
        bumper ${{ inputs.files }}

    - if: ${{ inputs.skip_deps == 'true' }}
      shell: bash
      run: ./bumper.sh ${{ inputs.files }}
