name: bumper
description: git version bumping action
author: trev
branding:
  icon: anchor
  color: gray-dark

inputs:
  files:
    description: list of files to look for version strings
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if [ -z "$(git config user.name)" ]; then
          echo "no user found, using default"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        fi

        echo "git user: $(git config user.name) <$(git config user.email)>"

    - shell: bash
      id: shell
      continue-on-error: true
      run: ./bumper.sh ${{ inputs.files }}

    - if: ${{ steps.shell.conclusion == 'failure' }}
      shell: bash
      run: |
        echo "bumping with just the script failed, trying with deb package"
        wget https://github.com/spotdemo4/bumper/releases/download/v0.1.1/bumper_0.1.1_amd64.deb
        sudo dpkg -i bumper_0.1.1_amd64.deb
        bumper ${{ inputs.files }}
