name: bumper
description: git version bumping action
author: trev
branding:
  icon: anchor
  color: gray-dark

inputs:
  files:
    description: list of files to manually bump versions in
    required: false
  commit:
    description: commit changes
    required: false
    default: "true"
  push:
    description: push changes
    required: false
    default: "true"
  major_types:
    description: commit types that trigger a major version bump
    required: false
  minor_types:
    description: commit types that trigger a minor version bump
    required: false
  patch_types:
    description: commit types that trigger a patch version bump
    required: false
  skip_scopes:
    description: commit scopes to skip
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::group::Check git user"
        if [ -z "$(git config user.name)" ]; then
          echo "no user found, using default"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        fi
        echo "::endgroup::"

        echo "git user: $(git config user.name) <$(git config user.email)>"

    - shell: bash
      run: |
        echo "::group::Check nix-update"
        if command -v nix &> /dev/null && ! command -v nix-update &> /dev/null; then
          echo "nix-update not found, installing via nix"

          UPDATE_PATH=$(nix shell nixpkgs#nix-update \
            --inputs-from . \
            --command bash \
            -c "which nix-update")
          echo "$(dirname "${UPDATE_PATH}")" >> "${GITHUB_PATH}"
        fi
        echo "::endgroup::"

    - shell: bash
      id: bumper
      env:
        FILES: ${{ inputs.files }}
        COMMIT: ${{ inputs.commit }}
        PUSH: ${{ inputs.push }}
        MAJOR_TYPES: ${{ inputs.major_types }}
        MINOR_TYPES: ${{ inputs.minor_types }}
        PATCH_TYPES: ${{ inputs.patch_types }}
        SKIP_SCOPES: ${{ inputs.skip_scopes }}
        DEBUG: ${{ runner.debug }}
      run: |
        chmod +x "${{ github.action_path }}/bumper.sh"
        if ! "${{ github.action_path }}/bumper.sh"; then
          if [[ "${?}" -eq 1 ]]; then
            exit 1
          fi

          echo "missing dependency, falling back to binary"
          wget "https://github.com/spotdemo4/bumper/releases/download/v0.1.20/bumper-x86_64-linux" -O "${{ github.action_path }}/bumper"
          chmod +x "${{ github.action_path }}/bumper"
          "${{ github.action_path }}/bumper"
        fi
