name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-26.04
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@c7537bc73ce11ca01e53bd9d119d6e46363f9888 # v1.65.0
        with:
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: |
            packages.x86_64-linux.default.x86_64-unknown-linux-musl
            packages.x86_64-linux.default.aarch64-unknown-linux-musl
            packages.x86_64-linux.default.armv7l-unknown-linux-musleabihf
            packages.x86_64-linux.default.x86_64-w64-mingw32
            packages.x86_64-linux.default.arm64-apple-darwin
            images.x86_64-linux.default.x86_64-unknown-linux-gnu
            images.x86_64-linux.default.aarch64-unknown-linux-gnu
            images.x86_64-linux.default.armv7l-unknown-linux-gnueabihf

  check:
    needs: release
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Dry run
        uses: $/
        with:
          commit: false
          tag: false
          push: false
          force: true
